//! gRPC message types + service traits for nine-snake v0.3.
//!
//! In a build-environment with `cargo` available these types would be
//! generated by `tonic_build::compile_protos` from
//! `proto/nine_snake.proto`. Because the v0.3 hand-off happens in an
//! environment without `cargo`, the generation step is **simulated**
//! by this file: every proto message is mirrored as a plain Rust
//! struct that round-trips through a JSON body wrapped in a single
//! `prost` field.
//!
//! v0.5 will replace this hand-rolled module with the real generated
//! code; the *public* API (struct names, field names, service
//! methods) is identical so the migration is mechanical.

use serde::{Deserialize, Serialize};

/// One byte string is exactly what tonic transports under the hood.
/// We keep this newtype so the call-sites read like the real
/// `prost::Message` API.
pub type Bytes = Vec<u8>;

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
#[derive(Default)]
pub enum MemoryLayer {
    #[default]
    Unspecified = 0,
    L0 = 1,
    L1 = 2,
    L2 = 3,
    L3 = 4,
    L4 = 5,
    L5 = 6,
    L6 = 7,
    L7 = 8,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
#[derive(Default)]
pub enum MemoryType {
    #[default]
    Unspecified = 0,
    Semantic = 1,
    Episodic = 2,
    Procedural = 3,
    Emotional = 4,
    Metacognitive = 5,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
#[derive(Default)]
pub enum AgentKind {
    #[default]
    Unspecified = 0,
    Coder = 1,
    Writer = 2,
    Reviewer = 3,
}

// ---------------------------------------------------------------------------
// Common messages
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Memory {
    pub id: String,
    #[serde(rename = "memoryType")]
    pub memory_type: MemoryType,
    pub layer: MemoryLayer,
    pub content: String,
    #[serde(rename = "summary50")]
    pub summary_50: String,
    #[serde(rename = "summary150")]
    pub summary_150: String,
    #[serde(rename = "summary500")]
    pub summary_500: String,
    #[serde(rename = "summary2000")]
    pub summary_2000: String,
    pub importance: f32,
    #[serde(rename = "accessCount")]
    pub access_count: u32,
    #[serde(rename = "lastAccess")]
    pub last_access: i64,
    #[serde(rename = "createdAt")]
    pub created_at: i64,
    pub source: String,
    #[serde(rename = "metadataJson")]
    pub metadata_json: String,
    #[serde(rename = "compressedFrom")]
    pub compressed_from: String,
    #[serde(rename = "compressionGen")]
    pub compression_gen: u32,
    pub pinned: bool,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ErrorInfo {
    pub code: String,
    pub message: String,
}

// ---------------------------------------------------------------------------
// Memory service messages
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct StoreMemoryRequest {
    pub content: String,
    #[serde(rename = "memoryType")]
    pub memory_type: MemoryType,
    pub layer: MemoryLayer,
    pub source: String,
    #[serde(rename = "metadataJson")]
    pub metadata_json: String,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct StoreMemoryResponse {
    pub id: String,
    pub merged: bool,
    pub similarity: f32,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetMemoryRequest {
    pub id: String,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SearchRequest {
    pub query: String,
    pub k: u32,
    pub layer: MemoryLayer,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SearchHit {
    pub memory: Memory,
    pub score: f32,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SearchResponse {
    pub hits: Vec<SearchHit>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListRecentRequest {
    pub limit: u32,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListRecentResponse {
    pub memories: Vec<Memory>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UpdateImportanceRequest {
    pub id: String,
    pub importance: f32,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct DeleteRequest {
    pub id: String,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct DeleteResponse {
    pub deleted: bool,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetManyRequest {
    pub ids: Vec<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetManyResponse {
    pub memories: Vec<Memory>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct StatsRequest {}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct StatsResponse {
    #[serde(rename = "totalMemories")]
    pub total_memories: u64,
    #[serde(rename = "byLayerL0")]
    pub by_layer_l0: u64,
    #[serde(rename = "byLayerL1")]
    pub by_layer_l1: u64,
    #[serde(rename = "byLayerL2")]
    pub by_layer_l2: u64,
    #[serde(rename = "byLayerL3")]
    pub by_layer_l3: u64,
    #[serde(rename = "byLayerL4")]
    pub by_layer_l4: u64,
    #[serde(rename = "byLayerL5")]
    pub by_layer_l5: u64,
    #[serde(rename = "byLayerL6")]
    pub by_layer_l6: u64,
    #[serde(rename = "byLayerL7")]
    pub by_layer_l7: u64,
}

// ---------------------------------------------------------------------------
// Swarm service messages
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Agent {
    pub kind: AgentKind,
    pub name: String,
    #[serde(rename = "systemPrompt")]
    pub system_prompt: String,
    pub description: String,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct AgentOutput {
    pub kind: AgentKind,
    pub author: String,
    pub body: String,
    pub confidence: f32,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SwarmRequest {
    pub description: String,
    pub pipeline: Vec<AgentKind>,
    #[serde(rename = "maxRetries")]
    pub max_retries: u32,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SwarmResponse {
    pub approved: bool,
    pub verdict: String,
    pub outputs: Vec<AgentOutput>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListAgentsRequest {}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListAgentsResponse {
    pub agents: Vec<Agent>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetAgentRequest {
    pub kind: AgentKind,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct StreamEventsRequest {
    #[serde(rename = "taskId")]
    pub task_id: String,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SwarmEvent {
    #[serde(rename = "eventType")]
    pub event_type: String,
    pub agent: AgentKind,
    pub body: String,
    pub ts: i64,
}

// ---------------------------------------------------------------------------
// Reflect service messages
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Reflection {
    pub id: String,
    #[serde(rename = "sourceMemories")]
    pub source_memories: Vec<String>,
    pub content: String,
    pub layer: MemoryLayer,
    #[serde(rename = "memoryType")]
    pub memory_type: MemoryType,
    pub importance: f32,
    #[serde(rename = "triggerKind")]
    pub trigger_kind: String,
    pub lessons: Vec<String>,
    pub confidence: f32,
    #[serde(rename = "createdAt")]
    pub created_at: i64,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ReflectRequest {}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ReflectResponse {
    pub reflections: Vec<Reflection>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListReflectionsRequest {
    pub limit: u32,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListReflectionsResponse {
    pub reflections: Vec<Reflection>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetReflectionRequest {
    pub id: String,
}

// ---------------------------------------------------------------------------
// LLM service messages
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ChatMessage {
    pub role: String,
    pub content: String,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CompleteRequest {
    pub prompt: String,
    pub model: String,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CompleteResponse {
    pub text: String,
    pub model: String,
    #[serde(rename = "evalCount")]
    pub eval_count: i64,
    #[serde(rename = "totalDurationNs")]
    pub total_duration_ns: i64,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ChatRequest {
    pub messages: Vec<ChatMessage>,
    pub model: String,
    pub temperature: f32,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ChatResponse {
    pub message: ChatMessage,
    pub model: String,
    #[serde(rename = "evalCount")]
    pub eval_count: i64,
    #[serde(rename = "totalDurationNs")]
    pub total_duration_ns: i64,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct EmbedRequest {
    pub text: String,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct EmbedResponse {
    pub vector: Vec<f32>,
    pub dim: u32,
}

// ---------------------------------------------------------------------------
// Skill service messages
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Skill {
    pub id: String,
    pub name: String,
    pub description: String,
    pub code: String,
    pub language: String,
    pub tags: Vec<String>,
    #[serde(rename = "usageCount")]
    pub usage_count: u32,
    #[serde(rename = "avgRating")]
    pub avg_rating: f32,
    #[serde(rename = "ratingCount")]
    pub rating_count: u32,
    #[serde(rename = "createdAt")]
    pub created_at: i64,
    #[serde(rename = "updatedAt")]
    pub updated_at: i64,
    #[serde(rename = "sourceMemoryId")]
    pub source_memory_id: String,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SkillResult {
    #[serde(rename = "skillId")]
    pub skill_id: String,
    pub output: String,
    #[serde(rename = "executionTimeMs")]
    pub execution_time_ms: u64,
    #[serde(rename = "tokensUsed")]
    pub tokens_used: u32,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CreateSkillRequest {
    pub name: String,
    pub description: String,
    pub code: String,
    pub language: String,
    pub tags: Vec<String>,
    #[serde(rename = "sourceMemoryId")]
    pub source_memory_id: String,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UseSkillRequest {
    pub id: String,
    pub params: std::collections::HashMap<String, String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UseSkillResponse {
    pub result: SkillResult,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct RateSkillRequest {
    pub id: String,
    pub rating: f32,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListSkillsRequest {
    pub language: String,
    pub tag: String,
    pub limit: u32,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListSkillsResponse {
    pub skills: Vec<Skill>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SearchSkillsRequest {
    pub query: String,
    pub limit: u32,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SearchSkillsResponse {
    pub skills: Vec<Skill>,
}

// ---------------------------------------------------------------------------
// Wire codec
// ---------------------------------------------------------------------------
//
// The real tonic-generated code would derive `prost::Message` on
// every type above and call `encode_length_delimited` /
// `decode_length_delimited` on the wire. We use a tiny JSON
// indirection that maps each message to a single-length-prefixed
// JSON blob, which keeps the server stub honest about its
// `tonic::Request<Bytes>` boundary and lets the v0.5 generated code
// slot in cleanly.

/// JSON wrapper used as the on-wire body for every gRPC method.
#[derive(Debug, Clone, Serialize, serde::Deserialize)]
pub struct JsonBody<T>(pub T);

impl<T> JsonBody<T>
where
    T: Serialize,
{
    pub fn encode(&self) -> Result<Bytes, serde_json::Error> {
        serde_json::to_vec(&self.0)
    }
}

impl<T> JsonBody<T>
where
    T: for<'de> Deserialize<'de>,
{
    pub fn decode(bytes: &[u8]) -> Result<Self, serde_json::Error> {
        serde_json::from_slice(bytes).map(JsonBody)
    }
}
